import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-loyalty-points-partner-settlement",
  "engine": "recovery",
  "title": "Loyalty Points Partner Settlement",
  "shortTitle": "Loyalty Points Partner Settlement",
  "tagline": "Quantify, recover, and prevent financial leakage through loyalty points partner settlement",
  "industry": "Loyalty Financial Operations",
  "uiPort": 4622,
  "apiPort": 5622,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Loyalty Points Partner Settlement converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "receivedSettlement",
    "expectedKey": "expectedSettlement",
    "actualLabel": "Received Partner Settlement",
    "expectedLabel": "Calculated Partner Settlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Loyalty Points Partner Settlement evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("partner-agreement-library","LPP01","Partner agreement library","Execute partner agreement library using loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash.","Produce a governed partner agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Loyalty Partner","text","Program / Loyalty Partner · Standard Case"],["caseReference","Partner agreement library Reference","text","LPP01-2026-001"],["receivedSettlement","Received Partner Settlement","currency",993500],["expectedSettlement","Calculated Partner Settlement","currency",1172330],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner agreement library case","Member account registry case","Earn-event ingestion case","Redemption-event ingestion case","Transfer conversion ratios case"]}),
feature("member-account-registry","LPP02","Member account registry","Execute member account registry using loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash.","Produce a governed member account registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Loyalty Partner","text","Program / Loyalty Partner · Standard Case"],["caseReference","Member account registry Reference","text","LPP02-2026-001"],["receivedSettlement","Received Partner Settlement","currency",993500],["expectedSettlement","Calculated Partner Settlement","currency",1172330],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner agreement library case","Member account registry case","Earn-event ingestion case","Redemption-event ingestion case","Transfer conversion ratios case"]}),
feature("earn-event-ingestion","LPP03","Earn-event ingestion","Execute earn-event ingestion using loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash.","Produce a governed earn-event ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Loyalty Partner","text","Program / Loyalty Partner · Standard Case"],["caseReference","Earn-event ingestion Reference","text","LPP03-2026-001"],["receivedSettlement","Received Partner Settlement","currency",993500],["expectedSettlement","Calculated Partner Settlement","currency",1172330],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner agreement library case","Member account registry case","Earn-event ingestion case","Redemption-event ingestion case","Transfer conversion ratios case"]}),
feature("redemption-event-ingestion","LPP04","Redemption-event ingestion","Execute redemption-event ingestion using loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash.","Produce a governed redemption-event ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Loyalty Partner","text","Program / Loyalty Partner · Standard Case"],["caseReference","Redemption-event ingestion Reference","text","LPP04-2026-001"],["receivedSettlement","Received Partner Settlement","currency",993500],["expectedSettlement","Calculated Partner Settlement","currency",1172330],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner agreement library case","Member account registry case","Earn-event ingestion case","Redemption-event ingestion case","Transfer conversion ratios case"]}),
feature("transfer-conversion-ratios","LPP05","Transfer conversion ratios","Execute transfer conversion ratios using loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash.","Produce a governed transfer conversion ratios decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Loyalty Partner","text","Program / Loyalty Partner · Standard Case"],["caseReference","Transfer conversion ratios Reference","text","LPP05-2026-001"],["receivedSettlement","Received Partner Settlement","currency",993500],["expectedSettlement","Calculated Partner Settlement","currency",1172330],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner agreement library case","Member account registry case","Earn-event ingestion case","Redemption-event ingestion case","Transfer conversion ratios case"]}),
feature("partner-purchase-rate-calculation","LPP06","Partner purchase-rate calculation","Execute partner purchase-rate calculation using loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash.","Produce a governed partner purchase-rate calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Loyalty Partner","text","Program / Loyalty Partner · Standard Case"],["caseReference","Partner purchase-rate calculation Reference","text","LPP06-2026-001"],["receivedSettlement","Received Partner Settlement","currency",993500],["expectedSettlement","Calculated Partner Settlement","currency",1172330],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner agreement library case","Member account registry case","Earn-event ingestion case","Redemption-event ingestion case","Transfer conversion ratios case"]}),
feature("redemption-reimbursement","LPP07","Redemption reimbursement","Execute redemption reimbursement using loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash.","Produce a governed redemption reimbursement decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Loyalty Partner","text","Program / Loyalty Partner · Standard Case"],["caseReference","Redemption reimbursement Reference","text","LPP07-2026-001"],["receivedSettlement","Received Partner Settlement","currency",993500],["expectedSettlement","Calculated Partner Settlement","currency",1172330],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner agreement library case","Member account registry case","Earn-event ingestion case","Redemption-event ingestion case","Transfer conversion ratios case"]}),
feature("promotional-bonus-allocation","LPP08","Promotional bonus allocation","Execute promotional bonus allocation using loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash.","Produce a governed promotional bonus allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Loyalty Partner","text","Program / Loyalty Partner · Standard Case"],["caseReference","Promotional bonus allocation Reference","text","LPP08-2026-001"],["receivedSettlement","Received Partner Settlement","currency",993500],["expectedSettlement","Calculated Partner Settlement","currency",1172330],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner agreement library case","Member account registry case","Earn-event ingestion case","Redemption-event ingestion case","Transfer conversion ratios case"]}),
feature("reversal-refund-control","LPP09","Reversal refund control","Execute reversal refund control using loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash.","Produce a governed reversal refund control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Loyalty Partner","text","Program / Loyalty Partner · Standard Case"],["caseReference","Reversal refund control Reference","text","LPP09-2026-001"],["receivedSettlement","Received Partner Settlement","currency",993500],["expectedSettlement","Calculated Partner Settlement","currency",1172330],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner agreement library case","Member account registry case","Earn-event ingestion case","Redemption-event ingestion case","Transfer conversion ratios case"]}),
feature("expiration-breakage","LPP10","Expiration breakage","Execute expiration breakage using loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash.","Produce a governed expiration breakage decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Loyalty Partner","text","Program / Loyalty Partner · Standard Case"],["caseReference","Expiration breakage Reference","text","LPP10-2026-001"],["receivedSettlement","Received Partner Settlement","currency",993500],["expectedSettlement","Calculated Partner Settlement","currency",1172330],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner agreement library case","Member account registry case","Earn-event ingestion case","Redemption-event ingestion case","Transfer conversion ratios case"]}),
feature("fraud-duplicate-events","LPP11","Fraud duplicate events","Execute fraud duplicate events using loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash.","Produce a governed fraud duplicate events decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Loyalty Partner","text","Program / Loyalty Partner · Standard Case"],["caseReference","Fraud duplicate events Reference","text","LPP11-2026-001"],["receivedSettlement","Received Partner Settlement","currency",993500],["expectedSettlement","Calculated Partner Settlement","currency",1172330],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner agreement library case","Member account registry case","Earn-event ingestion case","Redemption-event ingestion case","Transfer conversion ratios case"]}),
feature("partner-statement-reconciliation","LPP12","Partner statement reconciliation","Execute partner statement reconciliation using loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash.","Produce a governed partner statement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Loyalty Partner","text","Program / Loyalty Partner · Standard Case"],["caseReference","Partner statement reconciliation Reference","text","LPP12-2026-001"],["receivedSettlement","Received Partner Settlement","currency",993500],["expectedSettlement","Calculated Partner Settlement","currency",1172330],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner agreement library case","Member account registry case","Earn-event ingestion case","Redemption-event ingestion case","Transfer conversion ratios case"]}),
feature("settlement-dispute-workflow","LPP13","Settlement dispute workflow","Execute settlement dispute workflow using loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash.","Produce a governed settlement dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Loyalty Partner","text","Program / Loyalty Partner · Standard Case"],["caseReference","Settlement dispute workflow Reference","text","LPP13-2026-001"],["receivedSettlement","Received Partner Settlement","currency",993500],["expectedSettlement","Calculated Partner Settlement","currency",1172330],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner agreement library case","Member account registry case","Earn-event ingestion case","Redemption-event ingestion case","Transfer conversion ratios case"]}),
feature("cash-reconciliation","LPP14","Cash reconciliation","Execute cash reconciliation using loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Loyalty Partner","text","Program / Loyalty Partner · Standard Case"],["caseReference","Cash reconciliation Reference","text","LPP14-2026-001"],["receivedSettlement","Received Partner Settlement","currency",993500],["expectedSettlement","Calculated Partner Settlement","currency",1172330],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner agreement library case","Member account registry case","Earn-event ingestion case","Redemption-event ingestion case","Transfer conversion ratios case"]}),
feature("partner-program-economics","LPP15","Partner program economics","Execute partner program economics using loyalty partner agreements, members, earn events, redemptions, transfers, conversion ratios, partner purchase rates, bonuses, reversals, expiration, statements, and cash.","Produce a governed partner program economics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Loyalty Partner","text","Program / Loyalty Partner · Standard Case"],["caseReference","Partner program economics Reference","text","LPP15-2026-001"],["receivedSettlement","Received Partner Settlement","currency",993500],["expectedSettlement","Calculated Partner Settlement","currency",1172330],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedSettlement",subjects:["Partner agreement library case","Member account registry case","Earn-event ingestion case","Redemption-event ingestion case","Transfer conversion ratios case"]})
]);
